### PR TITLE
Show an error when no package.json is found for builtin commands requiring it

### LINKED ISSUE #252: Running CLI and commands without package.json throws errors
**Enhancement** 

When `dojo` or associated commands are run in a directory without a `package.json` file, the CLI throws errors such as `Path must be a string. Received null`

Package Version: 3.0.0

**Code**

```dojo``` or ```dojo init``` in any directory without a `package.json`

**Expected behavior:**

The CLI to either behave as best as possible or give a meaningful error message if not.

**Actual behavior:**

Unhelpful end user errors

### PR DESCRIPTION
**Pull request by JamesMilnerUK**
**Type:** bug / feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code has been formatted with [`prettier`](https://prettier.io/) as per the [readme code style guidelines](./../#code-style)
* [x] Unit or Functional tests are included in the PR

**Description:**

Resolves #252

** Screenshot **

screenshot_20180815_175643

### CODE REVIEW

**Comment by agubler** [comment]
I'm still not sure about adding the warning whilst we have a common command that should and does work without a `package.json`. I can imagine that will be confusing.

**Comment by JamesMilnerUK** [comment]
@agubler we could perhaps make it more granular, i.e. when it actually tries to access `package.json`?

**Comment by agubler** [comment]
@JamesMilnerUK That's often done in the actual commands I think - which the CLI doesn't know about.

**Comment by JamesMilnerUK** [comment]
So for init for example it happens here:
https://github.com/dojo/cli/blob/master/src/commands/init.ts#L11
Version:
https://github.com/dojo/cli/blob/master/src/commands/version.ts#L43
I think this will also be a big offender:
https://github.com/dojo/cli/blob/master/src/config.ts#L3

It would be good to have a unified way of trying to access the package.json and then erroring if it fails, even if it's just for the builtins. What do you think @ant?

**Pull request closed without merging**
